### ISSUE TITLE
Scopes

### ISSUE THREAD

**Issue by advany** [azurystudio/authenticus#8]
### Which preset is this for?

None

### Code sample

```TypeScript
Hi there,

I tried v2. Seems like passing scopes and return url isn't working (or returning a proper url) for Google. Works on the old one with the same parameters...
```

### Version

2

### Consent

- [X] I made sure there's no open issue about this bug already.

**Comment by boywithkeyboard** [comment]
Hey @advany! Do you use the NPM or Deno version?

**Comment by boywithkeyboard** [comment]
@advany, I've looked into it and tried to fix the issue. Could you please fork the repository and try the `createAuthorizeUrl` method and the `Google` preset on the [fix/respect-scopes-join-char](https://github.com/azurystudio/authenticus/tree/fix/respect-scopes-join-char) branch to see whether the issue is resolved?

**Comment by advany** [comment]
That part works now. I am not sure why the getting the token isn't working:

`import { Google, getToken } from "authenticus";

export async function get({ params, request, redirect }) {
  const request_url = new URL(request.url);
  
  const protocol = request_url.protocol; // e.g. http:
  const host = request_url.hostname; 

  const base_path = `${protocol}//${host}`;

  let code = request_url.searchParams.get('code')

  console.log(code)

  const { access_token } = await getToken(Google, {
    clientId: "14011771513-1ndbp6df07ehbtf80gc7pjoiuod4pjmr.apps.googleusercontent.com",
    clientSecret: "xxx",
    code: code,
    redirectUri: `http://localhost:3000/seo_submit/callback`,
  });

  return new Response(access_token)
}`

Keep getting {"method":"getToken","response":{"error":"invalid_grant","error_description":"Bad Request"},"statusCode":400}

**Comment by advany** [comment]
This the problem is in the scope still...

I am passing     scopes: ["https://www.googleapis.com/auth/webmasters"],
but it isn't asking me for permissions for webmasters

**Comment by boywithkeyboard** [comment]
@advany Well, can you access the API endpoints you're trying to access?

**Comment by boywithkeyboard** [comment]
@advany I can't find a scope with the name `https://www.googleapis.com/auth/webmasters` in Google's Developer Console, are you sure you're on the right page?
![image](https://github.com/azurystudio/authenticus/assets/62482066/f1b59c95-bf45-4fde-b624-0efa32e4eb76)

**Comment by boywithkeyboard** [comment]
I've tested it myself and I can verify that it works as intended.

**Comment by boywithkeyboard** [comment]
```
{"method":"getToken","response":{"error":"invalid_grant","error_description":"Bad Request"},"statusCode":400}
```

@advany also, this error basically says that the `grant_type` property is invalid. The `grant_type` in the `getToken` method is always `authorization_code`, thus you **need** to retrieve the code from a authorization flow via the authorization url.

I can't reproduce your error though.
